<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Biblioteca ITCA</title>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="../resources/css/materialize.css">
	<link rel="stylesheet" href="../resources/css/estilo.css">
	<link rel="stylesheet" href="../resources/css/sweetalert.css">
	<script src="../resources/js/jquery.js"></script>
	<script src="../resources/js/materialize.js"></script>
	<script src="../resources/js/sweetalert.js"></script>
	<script src="../resources/js/filtrar.js"></script>
	<script>$().ready(function(){
		 $('select').material_select();
	
	});</script>
	<meta name=“viewport” content=“width=device-width”>
</head>
<body>
	<a href="index.php"><img src="../resources/imagenes/logoHd.jpg" alt="logo" class="logo"></a>

<nav>
	<div class="nav-wrapper red darken-4">
		<a href="#" class="brand-logo"> Biblioteca Sede Central</a>
		<ul id="nav-mobile" class="right hide-on-med-and-down">
			<li class="active"><a href="index.php">Catálogo</a></li>
			<?php  
			if (/*$_SESSION["rol"]*/1==1) 
			{
				echo '<li><a href="php/libros.php">Libros</a></li>';
				echo '<li><a href="php/prestamos.php">Prestamos</a></li>';
				echo '<li><a href="php/devoluciones.php">Devoluciones</a></li>';
				echo '<li><a href="php/pedidos.php">Pedidos</a></li>';
				echo '<li><a href="php/usuarios.php">Usuarios</a></li>';
			}
			else if($_SESSION["rol"]==2)
			{
				echo '<li><a href="php/libros.php">Libros</a></li>';
				echo '<li><a href="php/prestamos.php">Prestamos</a></li>';
				echo '<li><a href="php/devoluciones.php">Devoluciones</a></li>';
				echo '<li><a href="php/pedidos.php">Pedidos</a></li>';
			}
			else
			{
				echo '<li><a href="php/prestamos.php">Mis Prestamos</a></li>';
			}
			?>
			<li><a href="php/perfil.php">Perfil</a></li>
			<li><a href="php/procesos/logout.php"><i class="material-icons">power_settings_new</i></a></li>

		</ul>
	</div>
</nav>

<div class="row catalogo">
			<form id="frmBuscar">
				<div class="col s1">
					<h4>Filtrar:</h4>
				</div>
	        	<div class="input-field col s3">
	          		<input  type="search" id="busqueda">
	          		<label class="label-icon" for="search"><i class="material-icons">search</i></label>
	          		<i id="limpiarBusqueda" class="material-icons">close</i>
				</div>

				<div class="input-field col s3">
    				<select name="campo" id="campo">
				      <option value="todos">Todos</option>
				      <option value="titulo">Titulo</option>
				      <option value="codigo">Codigo</option>
				      <option value="autor">Autor</option>
				      <option value="descripcion">Descripción</option>
   					</select>
    				<label>Buscar por:</label>
  				</div>

  				<div class="input-field col s3">
    				<select name="categoria" id="categoria">
						<option value="todas">Todas</option>
	  				<?php
	  				foreach($categories as $category)
	  				{
	  					echo "<option value=" . $category["id"] . ">" . $category["nombre"] . "</option>";
	  				}

	  				?>
   					</select>
    				<label>Categoria:</label>
  				</div>

  				<button id="btnBuscar" type="submit" class="waves-effect waves-light btn red darken-4"><i class="material-icons">search</i>Buscar</button>
     		</form>
</div>


<div class="container menu">
	<div class="row ">
		<div class="col s12 l12 catalogo-libros" id="libros">
			
			<?php 
			foreach ($books as $libro) 
			{
        //$ncat = $category->filterByName($libro["categoria"]);
				//$cat = $ncat;
				echo '<div class="contenedor-img">';
			 	echo "<img class='cover' src='../resources/imagenes/" . $libro["imagen"] . "' alt='". $libro["titulo"] . "'>";
			 	echo '<a href="php/libro.php?l=' . $libro["codigo"] . '">';
			 	echo '<div class="overlay">';
    			echo '<div class="texto">';
    			echo "<h6 class='titulo'>" . $libro["titulo"] . "</h6>";
    			echo "<p class='descripcion'>" . $libro["descripcion"] . "</p>";
    			//echo "<p class='categoria'>Categoria: " . $cat["nombre"] . "</p>";
    			echo "</div>";
 				echo "</div>";
 				echo "</a>";
			 	echo "</div>";
			}
			 ?>



		</div>
	</div>
</div>

<footer class="page-footer red darken-4">
	<div class="container">
		<div class="row">
			<div class="col s9">
				<h5 class="white-text">Ubicación:</h5>
                		<p class="grey-text text-lighten-4"><i class="material-icons">location_on</i>Carretera a Santa Tecla km. 11, La Libertad, El Salvador C.A</p>
                		<p class="grey-text text-lighten-4"><i class="material-icons">phone</i> (503) 2132-7400</p>
			</div>
			<div class="col s3">
				<h5 class="white-text">Paginas Similares:</h5>
				<a href="https://www.biblionline.pearson.com/Pages/Default.aspx"><img src="../resources/imagenes/person.png" alt="Biblioteca Virtual Person" height="40" width="60"></a>
				<a href="https://muse.jhu.edu/"><img src="../resources/imagenes/muse.png" alt="proyecto muse" height="40" width="45"></a>
				<a href="http://site.ebrary.com"><img src="../resources/imagenes/ebrary.jpg" alt="Biblioteca ebrary" height="40" width="60"></a>
				<a href="http://www.ciberoteca.com/homecas.asp"><img src="../resources/imagenes/cabecera_ciberoteca.png" alt="ciberoteca" height="40" width="80"></a>
				<a href="http://www.oecd-ilibrary.org/"><img src="../resources/imagenes/oecd.png" alt="oecdlibrary" height="40" width="90"></a>

                		
			</div>
		</div>

	</div>
	<div class="footer-copyright">
			<div class="container">
				© 2017 Creado por alumnos de ITCA-FEPADE
			</div>
		</div>
</footer>

</body>
</html>